import type { User } from '@/types/auth';
import type { WorkListItem } from '@/types/work';
import type { FilterOptionsResponse } from '@/types/common';
import type { CostAnomalyItem } from '@/types/cost_anomaly';
import type { DuplicatePairItem } from '@/types/duplicate_work';
import type { FundAnomalyItem } from '@/types/fund_anomaly';
import type { DelayItem } from '@/types/delay';
import type { DistrictSummaryItem, MPSummaryItem } from '@/types/summaries';

export const MOCK_USERS: Record<string, User> = {
  'ministry@mplads.gov.in': {
    id: 1,
    email: 'ministry@mplads.gov.in',
    full_name: 'Dr. Ramesh Kumar (Central MoSPI Director)',
    role: 'MINISTRY',
    assigned_state: null,
    assigned_district: null,
    assigned_mp_name: null,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  'state.up@mplads.gov.in': {
    id: 2,
    email: 'state.up@mplads.gov.in',
    full_name: 'Shri Vikram Singh (State Nodal Officer)',
    role: 'STATE_OFFICER',
    assigned_state: 'UTTAR PRADESH',
    assigned_district: null,
    assigned_mp_name: null,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  'district.patna@mplads.gov.in': {
    id: 3,
    email: 'district.patna@mplads.gov.in',
    full_name: 'Smt. Anita Sharma (District Planning Officer)',
    role: 'DISTRICT_OFFICER',
    assigned_state: 'BIHAR',
    assigned_district: 'PATNA',
    assigned_mp_name: null,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  'mp.khalsa@mplads.gov.in': {
    id: 4,
    email: 'mp.khalsa@mplads.gov.in',
    full_name: 'Sarabjeet Singh Khalsa (MP)',
    role: 'MP',
    assigned_state: 'PUNJAB',
    assigned_district: null,
    assigned_mp_name: 'SARABJEET SINGH KHALSA',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
};

export const MOCK_FILTERS: FilterOptionsResponse = {
  states: ['UTTAR PRADESH', 'BIHAR', 'PUNJAB', 'MAHARASHTRA', 'TAMIL NADU', 'RAJASTHAN', 'WEST BENGAL'],
  districts: ['PATNA', 'LUCKNOW', 'FARIDKOT', 'PUNE', 'CHENNAI'],
  houses: ['LOK SABHA', 'RAJYA SABHA'],
  work_categories: [
    'Roads, Bridges & Pathways',
    'Drinking Water & Sanitation',
    'Education & Skill Infrastructure',
    'Public Health & Hospitals',
    'Community Halls & Sports Facilities',
    'Irrigation & Rural Electrification',
  ],
  work_statuses: ['Sanctioned', 'In Progress', 'Completed', 'Recommendation Received'],
  cost_severities: ['HIGH', 'MEDIUM', 'LOW'],
  duplicate_severities: ['HIGH', 'REVIEW', 'LOW'],
  fund_severities: ['HIGH', 'MEDIUM', 'LOW'],
  fund_audit_categories: ['ACTIVE_EXPENDITURE', 'NORMAL_AWAITING_DISBURSEMENT', 'DORMANT_SANCTION', 'STATUS_EXPENDITURE_MISMATCH'],
  delay_severities: ['HIGH', 'MEDIUM', 'LOW'],
  delay_types: ['RECOMMENDATION_TO_SANCTION_DELAY', 'SANCTION_TO_COMPLETION_DELAY', 'OPEN_WORK_AGING_STALLED'],
};

export const MOCK_WORKS: WorkListItem[] = [
  {
    work_id: 'WORK-2026-UP-001',
    house: 'LOK SABHA',
    work_description: 'Construction of 2.5km CC Road from NH-24 Junction to Primary School in District Luckow',
    sanction_amount: 4500000,
    amount_disbursed: 4500000,
    state: 'UTTAR PRADESH',
    district: 'LUCKNOW',
    ida: 'PWD Lucknow',
    mp_name: 'RAJNATH SINGH',
    constituency: 'LUCKNOW',
    work_category: 'Roads, Bridges & Pathways',
    work_type: 'INFRASTRUCTURE',
    work_status: 'Completed',
    recommended_date: '2025-02-10',
    sanction_date: '2025-03-15',
    completion_date: '2025-11-20',
    is_completed_flag: true,
  },
  {
    work_id: 'WORK-2026-BR-089',
    house: 'LOK SABHA',
    work_description: 'Installation of Solar Powered High-Mast Deep Borewell Water Plant in Kankarbagh Ward 12',
    sanction_amount: 2800000,
    amount_disbursed: 1400000,
    state: 'BIHAR',
    district: 'PATNA',
    ida: 'PHED Patna',
    mp_name: 'RUDY RAJIV PRATAP',
    constituency: 'SARAN',
    work_category: 'Drinking Water & Sanitation',
    work_type: 'WATER',
    work_status: 'In Progress',
    recommended_date: '2025-04-01',
    sanction_date: '2025-05-10',
    completion_date: null,
    is_completed_flag: false,
  },
  {
    work_id: 'WORK-2026-PB-042',
    house: 'LOK SABHA',
    work_description: 'Supply of Smart Class Digital Projectors and IT Lab Computers for Govt Senior Secondary School',
    sanction_amount: 7500000,
    amount_disbursed: 7500000,
    state: 'PUNJAB',
    district: 'FARIDKOT',
    ida: 'District Education Officer',
    mp_name: 'SARABJEET SINGH KHALSA',
    constituency: 'FARIDKOT',
    work_category: 'Education & Skill Infrastructure',
    work_type: 'EDUCATION',
    work_status: 'Completed',
    recommended_date: '2024-11-15',
    sanction_date: '2025-01-05',
    completion_date: '2025-09-12',
    is_completed_flag: true,
  },
  {
    work_id: 'WORK-2026-MH-112',
    house: 'LOK SABHA',
    work_description: 'Construction of Multipurpose Community Hall & Library Block in Baramati Taluka',
    sanction_amount: 12000000,
    amount_disbursed: 3000000,
    state: 'MAHARASHTRA',
    district: 'PUNE',
    ida: 'ZP Pune',
    mp_name: 'SUPRIYA SULE',
    constituency: 'BARAMATI',
    work_category: 'Community Halls & Sports Facilities',
    work_type: 'COMMUNITY',
    work_status: 'In Progress',
    recommended_date: '2024-06-10',
    sanction_date: '2024-09-01',
    completion_date: null,
    is_completed_flag: false,
  },
];

export const MOCK_COST_ANOMALIES: CostAnomalyItem[] = [
  {
    work_id: 'WORK-2026-UP-001',
    severity: 'HIGH',
    cost_anomaly_score: 0.88,
    raw_anomaly_score: 0.92,
    peer_group_used: 'UTTAR PRADESH :: Roads, Bridges & Pathways',
    peer_group_level: 'STATE_CATEGORY',
    peer_group_size: 1420,
    is_data_quality_exception: false,
    explanation: 'Sanction amount ₹45.00 L exceeds peer category median (₹21.00 L) by +114.2% across Uttar Pradesh.',
  },
  {
    work_id: 'WORK-2026-MH-112',
    severity: 'HIGH',
    cost_anomaly_score: 0.82,
    raw_anomaly_score: 0.85,
    peer_group_used: 'MAHARASHTRA :: Community Halls',
    peer_group_level: 'STATE_CATEGORY',
    peer_group_size: 680,
    is_data_quality_exception: false,
    explanation: 'Community hall outlay ₹1.20 Cr exceeds regional peer median (₹55.00 L) by +118.1%.',
  },
];

export const MOCK_DUPLICATE_WORKS: DuplicatePairItem[] = [
  {
    id: 101,
    work_id_1: 'WORK-2026-BR-089',
    work_id_2: 'WORK-2026-BR-090',
    duplicate_score: 0.94,
    severity: 'HIGH',
    confidence: 0.95,
    semantic_similarity: 0.96,
    amount_similarity: 0.98,
    days_diff: 4,
    structural_score: 0.90,
    date_proximity: 0.95,
    is_same_mp: true,
    is_same_constituency: true,
    explanation: 'High semantic match (96%) and identical amount ₹28.00 L sanctioned within 4 days in Patna district.',
  },
];

export const MOCK_FUND_ANOMALIES: FundAnomalyItem[] = [
  {
    work_id: 'WORK-2026-BR-089',
    severity: 'HIGH',
    fund_anomaly_score: 0.85,
    raw_score: 0.88,
    audit_category: 'ACTIVE_EXPENDITURE',
    utilization_ratio: 0.50,
    transaction_count: 3,
    payment_concentration_hhi: 0.92,
    days_to_first_disbursement: 45,
    total_disbursed_amount: 1400000,
    anomaly_reasons: ['HIGH_VENDOR_HHI'],
    explanation: 'High vendor payment concentration HHI (0.92) indicating single-vendor disbursement dominance.',
  },
];

export const MOCK_DELAYS: DelayItem[] = [
  {
    work_id: 'WORK-2026-MH-112',
    severity: 'HIGH',
    delay_score: 0.89,
    rec_to_sanc_days: 83,
    rec_to_sanc_delay_days: 8,
    rec_to_sanc_severity: 'HIGH',
    sanc_to_comp_days: 420,
    sanc_to_comp_delay_days: 55,
    sanc_to_comp_severity: 'HIGH',
    open_work_aging_days: 550,
    open_work_overdue_days: 185,
    open_work_aging_severity: 'HIGH',
    primary_delay_type: 'SANCTION_TO_COMPLETION_DELAY',
    active_delay_types: ['SANCTION_TO_COMPLETION_DELAY'],
    explanation: 'Work open aging (550 days) exceeds 365-day statutory execution deadline under Guideline Para 3.12.',
  },
];

export const MOCK_MP_SUMMARIES: MPSummaryItem[] = [
  {
    mp_name: 'SARABJEET SINGH KHALSA',
    house: 'LOK SABHA',
    state: 'PUNJAB',
    constituency: 'FARIDKOT',
    total_works: 42,
    total_sanctioned_amount: 85000000,
    completed_works: 31,
    completion_rate: 73.8,
    high_cost_anomalies: 2,
    high_duplicate_pairs: 1,
    high_fund_anomalies: 1,
    high_delays: 3,
  },
  {
    mp_name: 'RAJNATH SINGH',
    house: 'LOK SABHA',
    state: 'UTTAR PRADESH',
    constituency: 'LUCKNOW',
    total_works: 118,
    total_sanctioned_amount: 240000000,
    completed_works: 98,
    completion_rate: 83.1,
    high_cost_anomalies: 3,
    high_duplicate_pairs: 2,
    high_fund_anomalies: 2,
    high_delays: 4,
  },
  {
    mp_name: 'SUPRIYA SULE',
    house: 'LOK SABHA',
    state: 'MAHARASHTRA',
    constituency: 'BARAMATI',
    total_works: 85,
    total_sanctioned_amount: 190000000,
    completed_works: 62,
    completion_rate: 72.9,
    high_cost_anomalies: 4,
    high_duplicate_pairs: 3,
    high_fund_anomalies: 3,
    high_delays: 5,
  },
];

export const MOCK_DISTRICT_SUMMARIES: DistrictSummaryItem[] = [
  {
    district: 'LUCKNOW',
    state: 'UTTAR PRADESH',
    total_works: 15482,
    total_sanctioned_amount: 8421000000,
    total_disbursed_amount: 8385000000,
    high_cost_anomalies: 1240,
    high_duplicate_pairs: 2850,
    high_fund_anomalies: 2,
    high_delays: 7890,
  },
  {
    district: 'PATNA',
    state: 'BIHAR',
    total_works: 14490,
    total_sanctioned_amount: 7850000000,
    total_disbursed_amount: 7810000000,
    high_cost_anomalies: 1120,
    high_duplicate_pairs: 2410,
    high_fund_anomalies: 1,
    high_delays: 7240,
  },
  {
    district: 'MUMBAI SUBURBAN',
    state: 'MAHARASHTRA',
    total_works: 12850,
    total_sanctioned_amount: 7120000000,
    total_disbursed_amount: 7090000000,
    high_cost_anomalies: 980,
    high_duplicate_pairs: 2150,
    high_fund_anomalies: 1,
    high_delays: 6410,
  },
  {
    district: 'MURSHIDABAD',
    state: 'WEST BENGAL',
    total_works: 11930,
    total_sanctioned_amount: 6840000000,
    total_disbursed_amount: 6810000000,
    high_cost_anomalies: 890,
    high_duplicate_pairs: 1980,
    high_fund_anomalies: 1,
    high_delays: 5960,
  },
  {
    district: 'BENGALURU URBAN',
    state: 'KARNATAKA',
    total_works: 10849,
    total_sanctioned_amount: 6510000000,
    total_disbursed_amount: 6480000000,
    high_cost_anomalies: 820,
    high_duplicate_pairs: 1820,
    high_fund_anomalies: 1,
    high_delays: 5420,
  },
  {
    district: 'FARIDKOT',
    state: 'PUNJAB',
    total_works: 9850,
    total_sanctioned_amount: 5820000000,
    total_disbursed_amount: 5790000000,
    high_cost_anomalies: 740,
    high_duplicate_pairs: 1610,
    high_fund_anomalies: 1,
    high_delays: 4920,
  },
  {
    district: 'JAIPUR',
    state: 'RAJASTHAN',
    total_works: 9420,
    total_sanctioned_amount: 5420000000,
    total_disbursed_amount: 5390000000,
    high_cost_anomalies: 690,
    high_duplicate_pairs: 1540,
    high_fund_anomalies: 1,
    high_delays: 4710,
  },
  {
    district: 'AHMEDABAD',
    state: 'GUJARAT',
    total_works: 8960,
    total_sanctioned_amount: 5120000000,
    total_disbursed_amount: 5090000000,
    high_cost_anomalies: 650,
    high_duplicate_pairs: 1420,
    high_fund_anomalies: 1,
    high_delays: 4480,
  },
  {
    district: 'CHENNAI',
    state: 'TAMIL NADU',
    total_works: 8640,
    total_sanctioned_amount: 4910000000,
    total_disbursed_amount: 4890000000,
    high_cost_anomalies: 610,
    high_duplicate_pairs: 1350,
    high_fund_anomalies: 1,
    high_delays: 4320,
  },
  {
    district: 'HYDERABAD',
    state: 'TELANGANA',
    total_works: 8210,
    total_sanctioned_amount: 4680000000,
    total_disbursed_amount: 4660000000,
    high_cost_anomalies: 580,
    high_duplicate_pairs: 1280,
    high_fund_anomalies: 0,
    high_delays: 4105,
  },
  {
    district: 'NEW DELHI',
    state: 'DELHI',
    total_works: 7850,
    total_sanctioned_amount: 4450000000,
    total_disbursed_amount: 4430000000,
    high_cost_anomalies: 540,
    high_duplicate_pairs: 1210,
    high_fund_anomalies: 0,
    high_delays: 3925,
  },
  {
    district: 'KAMRUP METROPOLITAN',
    state: 'ASSAM',
    total_works: 7420,
    total_sanctioned_amount: 4210000000,
    total_disbursed_amount: 4190000000,
    high_cost_anomalies: 510,
    high_duplicate_pairs: 1140,
    high_fund_anomalies: 0,
    high_delays: 3710,
  },
  {
    district: 'BHOPAL',
    state: 'MADHYA PRADESH',
    total_works: 7120,
    total_sanctioned_amount: 3980000000,
    total_disbursed_amount: 3960000000,
    high_cost_anomalies: 480,
    high_duplicate_pairs: 1080,
    high_fund_anomalies: 0,
    high_delays: 3560,
  },
  {
    district: 'RAIPUR',
    state: 'CHHATTISGARH',
    total_works: 6850,
    total_sanctioned_amount: 3750000000,
    total_disbursed_amount: 3730000000,
    high_cost_anomalies: 450,
    high_duplicate_pairs: 1020,
    high_fund_anomalies: 0,
    high_delays: 3425,
  },
  {
    district: 'RANCHI',
    state: 'JHARKHAND',
    total_works: 6520,
    total_sanctioned_amount: 3520000000,
    total_disbursed_amount: 3500000000,
    high_cost_anomalies: 420,
    high_duplicate_pairs: 960,
    high_fund_anomalies: 0,
    high_delays: 3260,
  },
  {
    district: 'BHUBANESWAR',
    state: 'ODISHA',
    total_works: 6210,
    total_sanctioned_amount: 3320000000,
    total_disbursed_amount: 3300000000,
    high_cost_anomalies: 390,
    high_duplicate_pairs: 910,
    high_fund_anomalies: 0,
    high_delays: 3105,
  },
  {
    district: 'THIRUVANANTHAPURAM',
    state: 'KERALA',
    total_works: 5940,
    total_sanctioned_amount: 3110000000,
    total_disbursed_amount: 3100000000,
    high_cost_anomalies: 360,
    high_duplicate_pairs: 850,
    high_fund_anomalies: 0,
    high_delays: 2970,
  },
  {
    district: 'VISAKHAPATNAM',
    state: 'ANDHRA PRADESH',
    total_works: 5680,
    total_sanctioned_amount: 2940000000,
    total_disbursed_amount: 2930000000,
    high_cost_anomalies: 330,
    high_duplicate_pairs: 800,
    high_fund_anomalies: 0,
    high_delays: 2840,
  },
  {
    district: 'SRINAGAR',
    state: 'JAMMU AND KASHMIR',
    total_works: 5410,
    total_sanctioned_amount: 2780000000,
    total_disbursed_amount: 2770000000,
    high_cost_anomalies: 300,
    high_duplicate_pairs: 740,
    high_fund_anomalies: 0,
    high_delays: 2705,
  },
  {
    district: 'DEHRADUN',
    state: 'UTTARAKHAND',
    total_works: 5120,
    total_sanctioned_amount: 2610000000,
    total_disbursed_amount: 2600000000,
    high_cost_anomalies: 270,
    high_duplicate_pairs: 690,
    high_fund_anomalies: 0,
    high_delays: 2560,
  },
  {
    district: 'SHIMLA',
    state: 'HIMACHAL PRADESH',
    total_works: 4850,
    total_sanctioned_amount: 2450000000,
    total_disbursed_amount: 2440000000,
    high_cost_anomalies: 240,
    high_duplicate_pairs: 630,
    high_fund_anomalies: 0,
    high_delays: 2425,
  },
  {
    district: 'GURUGRAM',
    state: 'HARYANA',
    total_works: 4620,
    total_sanctioned_amount: 2310000000,
    total_disbursed_amount: 2300000000,
    high_cost_anomalies: 220,
    high_duplicate_pairs: 580,
    high_fund_anomalies: 0,
    high_delays: 2310,
  },
  {
    district: 'IMPHAL WEST',
    state: 'MANIPUR',
    total_works: 4380,
    total_sanctioned_amount: 2180000000,
    total_disbursed_amount: 2170000000,
    high_cost_anomalies: 190,
    high_duplicate_pairs: 530,
    high_fund_anomalies: 0,
    high_delays: 2190,
  },
  {
    district: 'SHILLONG',
    state: 'MEGHALAYA',
    total_works: 4120,
    total_sanctioned_amount: 2040000000,
    total_disbursed_amount: 2030000000,
    high_cost_anomalies: 170,
    high_duplicate_pairs: 480,
    high_fund_anomalies: 0,
    high_delays: 2060,
  },
  {
    district: 'AGARTALA',
    state: 'TRIPURA',
    total_works: 3890,
    total_sanctioned_amount: 1920000000,
    total_disbursed_amount: 1910000000,
    high_cost_anomalies: 150,
    high_duplicate_pairs: 440,
    high_fund_anomalies: 0,
    high_delays: 1945,
  },
  {
    district: 'AIZAWL',
    state: 'MIZORAM',
    total_works: 3650,
    total_sanctioned_amount: 1810000000,
    total_disbursed_amount: 1800000000,
    high_cost_anomalies: 130,
    high_duplicate_pairs: 400,
    high_fund_anomalies: 0,
    high_delays: 1825,
  },
  {
    district: 'KOHIMA',
    state: 'NAGALAND',
    total_works: 3410,
    total_sanctioned_amount: 1700000000,
    total_disbursed_amount: 1690000000,
    high_cost_anomalies: 110,
    high_duplicate_pairs: 360,
    high_fund_anomalies: 0,
    high_delays: 1705,
  },
  {
    district: 'GANGTOK',
    state: 'SIKKIM',
    total_works: 3180,
    total_sanctioned_amount: 1590000000,
    total_disbursed_amount: 1580000000,
    high_cost_anomalies: 90,
    high_duplicate_pairs: 320,
    high_fund_anomalies: 0,
    high_delays: 1590,
  },
  {
    district: 'PANAJI',
    state: 'GOA',
    total_works: 2950,
    total_sanctioned_amount: 1480000000,
    total_disbursed_amount: 1470000000,
    high_cost_anomalies: 70,
    high_duplicate_pairs: 280,
    high_fund_anomalies: 0,
    high_delays: 1475,
  },
  {
    district: 'ITANAGAR',
    state: 'ARUNACHAL PRADESH',
    total_works: 2710,
    total_sanctioned_amount: 1370000000,
    total_disbursed_amount: 1360000000,
    high_cost_anomalies: 50,
    high_duplicate_pairs: 240,
    high_fund_anomalies: 0,
    high_delays: 1355,
  },
];
