import type { User } from '@/types/auth';
import type { WorkListItem } from '@/types/work';
import type { FilterOptionsResponse } from '@/types/common';
import type { CostAnomalyItem } from '@/types/cost_anomaly';
import type { DuplicatePairItem } from '@/types/duplicate_work';
import type { FundAnomalyItem } from '@/types/fund_anomaly';
import type { DelayItem } from '@/types/delay';
import type { DistrictSummaryItem, MPSummaryItem } from '@/types/summaries';

export const MOCK_USERS: Record<string, User> = {
  'ministry@mplads.gov.in': {
    id: 1,
    email: 'ministry@mplads.gov.in',
    full_name: 'Dr. Ramesh Kumar (Central MoSPI Director)',
    role: 'MINISTRY',
    assigned_state: null,
    assigned_district: null,
    assigned_mp_name: null,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  'state.up@mplads.gov.in': {
    id: 2,
    email: 'state.up@mplads.gov.in',
    full_name: 'Shri Vikram Singh (State Nodal Officer)',
    role: 'STATE_OFFICER',
    assigned_state: 'UTTAR PRADESH',
    assigned_district: null,
    assigned_mp_name: null,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  'district.patna@mplads.gov.in': {
    id: 3,
    email: 'district.patna@mplads.gov.in',
    full_name: 'Smt. Anita Sharma (District Planning Officer)',
    role: 'DISTRICT_OFFICER',
    assigned_state: 'BIHAR',
    assigned_district: 'PATNA',
    assigned_mp_name: null,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  'mp.khalsa@mplads.gov.in': {
    id: 4,
    email: 'mp.khalsa@mplads.gov.in',
    full_name: 'Sarabjeet Singh Khalsa (MP)',
    role: 'MP',
    assigned_state: 'PUNJAB',
    assigned_district: null,
    assigned_mp_name: 'SARABJEET SINGH KHALSA',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
};

export const MOCK_FILTERS: FilterOptionsResponse = {
  states: ['UTTAR PRADESH', 'BIHAR', 'PUNJAB', 'MAHARASHTRA', 'TAMIL NADU', 'RAJASTHAN', 'WEST BENGAL'],
  districts: ['PATNA', 'LUCKNOW', 'FARIDKOT', 'PUNE', 'CHENNAI'],
  houses: ['LOK SABHA', 'RAJYA SABHA'],
  work_categories: [
    'Roads, Bridges & Pathways',
    'Drinking Water & Sanitation',
    'Education & Skill Infrastructure',
    'Public Health & Hospitals',
    'Community Halls & Sports Facilities',
    'Irrigation & Rural Electrification',
  ],
  work_statuses: ['Sanctioned', 'In Progress', 'Completed', 'Recommendation Received'],
  cost_severities: ['HIGH', 'MEDIUM', 'LOW'],
  duplicate_severities: ['HIGH', 'REVIEW', 'LOW'],
  fund_severities: ['HIGH', 'MEDIUM', 'LOW'],
  fund_audit_categories: ['ACTIVE_EXPENDITURE', 'NORMAL_AWAITING_DISBURSEMENT', 'DORMANT_SANCTION', 'STATUS_EXPENDITURE_MISMATCH'],
  delay_severities: ['HIGH', 'MEDIUM', 'LOW'],
  delay_types: ['RECOMMENDATION_TO_SANCTION_DELAY', 'SANCTION_TO_COMPLETION_DELAY', 'OPEN_WORK_AGING_STALLED'],
};

export const MOCK_WORKS: WorkListItem[] = [
  {
    work_id: 'WORK-2026-UP-001',
    house: 'LOK SABHA',
    work_description: 'Construction of 2.5km CC Road from NH-24 Junction to Primary School in District Luckow',
    sanction_amount: 4500000,
    amount_disbursed: 4500000,
    state: 'UTTAR PRADESH',
    district: 'LUCKNOW',
    ida: 'PWD Lucknow',
    mp_name: 'RAJNATH SINGH',
    constituency: 'LUCKNOW',
    work_category: 'Roads, Bridges & Pathways',
    work_type: 'INFRASTRUCTURE',
    work_status: 'Completed',
    recommended_date: '2025-02-10',
    sanction_date: '2025-03-15',
    completion_date: '2025-11-20',
    is_completed_flag: true,
  },
  {
    work_id: 'WORK-2026-BR-089',
    house: 'LOK SABHA',
    work_description: 'Installation of Solar Powered High-Mast Deep Borewell Water Plant in Kankarbagh Ward 12',
    sanction_amount: 2800000,
    amount_disbursed: 1400000,
    state: 'BIHAR',
    district: 'PATNA',
    ida: 'PHED Patna',
    mp_name: 'RUDY RAJIV PRATAP',
    constituency: 'SARAN',
    work_category: 'Drinking Water & Sanitation',
    work_type: 'WATER',
    work_status: 'In Progress',
    recommended_date: '2025-04-01',
    sanction_date: '2025-05-10',
    completion_date: null,
    is_completed_flag: false,
  },
  {
    work_id: 'WORK-2026-PB-042',
    house: 'LOK SABHA',
    work_description: 'Supply of Smart Class Digital Projectors and IT Lab Computers for Govt Senior Secondary School',
    sanction_amount: 7500000,
    amount_disbursed: 7500000,
    state: 'PUNJAB',
    district: 'FARIDKOT',
    ida: 'District Education Officer',
    mp_name: 'SARABJEET SINGH KHALSA',
    constituency: 'FARIDKOT',
    work_category: 'Education & Skill Infrastructure',
    work_type: 'EDUCATION',
    work_status: 'Completed',
    recommended_date: '2024-11-15',
    sanction_date: '2025-01-05',
    completion_date: '2025-09-12',
    is_completed_flag: true,
  },
  {
    work_id: 'WORK-2026-MH-112',
    house: 'LOK SABHA',
    work_description: 'Construction of Multipurpose Community Hall & Library Block in Baramati Taluka',
    sanction_amount: 12000000,
    amount_disbursed: 3000000,
    state: 'MAHARASHTRA',
    district: 'PUNE',
    ida: 'ZP Pune',
    mp_name: 'SUPRIYA SULE',
    constituency: 'BARAMATI',
    work_category: 'Community Halls & Sports Facilities',
    work_type: 'COMMUNITY',
    work_status: 'In Progress',
    recommended_date: '2024-06-10',
    sanction_date: '2024-09-01',
    completion_date: null,
    is_completed_flag: false,
  },
];

export const MOCK_COST_ANOMALIES: CostAnomalyItem[] = [
  {
    work_id: 'WORK-2026-UP-001',
    severity: 'HIGH',
    cost_anomaly_score: 0.88,
    raw_anomaly_score: 0.92,
    peer_group_used: 'UTTAR PRADESH :: Roads, Bridges & Pathways',
    peer_group_level: 'STATE_CATEGORY',
    peer_group_size: 1420,
    is_data_quality_exception: false,
    explanation: 'Sanction amount ₹45.00 L exceeds peer category median (₹21.00 L) by +114.2% across Uttar Pradesh.',
  },
  {
    work_id: 'WORK-2026-MH-112',
    severity: 'HIGH',
    cost_anomaly_score: 0.82,
    raw_anomaly_score: 0.85,
    peer_group_used: 'MAHARASHTRA :: Community Halls',
    peer_group_level: 'STATE_CATEGORY',
    peer_group_size: 680,
    is_data_quality_exception: false,
    explanation: 'Community hall outlay ₹1.20 Cr exceeds regional peer median (₹55.00 L) by +118.1%.',
  },
];

export const MOCK_DUPLICATE_WORKS: DuplicatePairItem[] = [
  {
    id: 101,
    work_id_1: 'WORK-2026-BR-089',
    work_id_2: 'WORK-2026-BR-090',
    duplicate_score: 0.94,
    severity: 'HIGH',
    confidence: 0.95,
    semantic_similarity: 0.96,
    amount_similarity: 0.98,
    days_diff: 4,
    structural_score: 0.90,
    date_proximity: 0.95,
    is_same_mp: true,
    is_same_constituency: true,
    explanation: 'High semantic match (96%) and identical amount ₹28.00 L sanctioned within 4 days in Patna district.',
  },
];

export const MOCK_FUND_ANOMALIES: FundAnomalyItem[] = [
  {
    work_id: 'WORK-2026-BR-089',
    severity: 'HIGH',
    fund_anomaly_score: 0.85,
    raw_score: 0.88,
    audit_category: 'ACTIVE_EXPENDITURE',
    utilization_ratio: 0.50,
    transaction_count: 3,
    payment_concentration_hhi: 0.92,
    days_to_first_disbursement: 45,
    total_disbursed_amount: 1400000,
    anomaly_reasons: ['HIGH_VENDOR_HHI'],
    explanation: 'High vendor payment concentration HHI (0.92) indicating single-vendor disbursement dominance.',
  },
];

export const MOCK_DELAYS: DelayItem[] = [
  {
    work_id: 'WORK-2026-MH-112',
    severity: 'HIGH',
    delay_score: 0.89,
    rec_to_sanc_days: 83,
    rec_to_sanc_delay_days: 8,
    rec_to_sanc_severity: 'HIGH',
    sanc_to_comp_days: 420,
    sanc_to_comp_delay_days: 55,
    sanc_to_comp_severity: 'HIGH',
    open_work_aging_days: 550,
    open_work_overdue_days: 185,
    open_work_aging_severity: 'HIGH',
    primary_delay_type: 'SANCTION_TO_COMPLETION_DELAY',
    active_delay_types: ['SANCTION_TO_COMPLETION_DELAY'],
    explanation: 'Work open aging (550 days) exceeds 365-day statutory execution deadline under Guideline Para 3.12.',
  },
];

export const MOCK_MP_SUMMARIES: MPSummaryItem[] = [
  {
    mp_name: 'SARABJEET SINGH KHALSA',
    house: 'LOK SABHA',
    state: 'PUNJAB',
    constituency: 'FARIDKOT',
    total_works: 42,
    total_sanctioned_amount: 85000000,
    completed_works: 31,
    completion_rate: 73.8,
    high_cost_anomalies: 2,
    high_duplicate_pairs: 1,
    high_fund_anomalies: 1,
    high_delays: 3,
  },
  {
    mp_name: 'RAJNATH SINGH',
    house: 'LOK SABHA',
    state: 'UTTAR PRADESH',
    constituency: 'LUCKNOW',
    total_works: 118,
    total_sanctioned_amount: 240000000,
    completed_works: 98,
    completion_rate: 83.1,
    high_cost_anomalies: 3,
    high_duplicate_pairs: 2,
    high_fund_anomalies: 2,
    high_delays: 4,
  },
  {
    mp_name: 'SUPRIYA SULE',
    house: 'LOK SABHA',
    state: 'MAHARASHTRA',
    constituency: 'BARAMATI',
    total_works: 85,
    total_sanctioned_amount: 190000000,
    completed_works: 62,
    completion_rate: 72.9,
    high_cost_anomalies: 4,
    high_duplicate_pairs: 3,
    high_fund_anomalies: 3,
    high_delays: 5,
  },
];

export const MOCK_DISTRICT_SUMMARIES: DistrictSummaryItem[] = [
  {
    district: 'LUCKNOW',
    state: 'UTTAR PRADESH',
    total_works: 14612,
    total_sanctioned_amount: 7814429239,
    total_disbursed_amount: 7779697338,
    high_cost_anomalies: 1262,
    high_duplicate_pairs: 2888,
    high_fund_anomalies: 1,
    high_delays: 7576,
  },
  {
    district: 'PATNA',
    state: 'BIHAR',
    total_works: 12950,
    total_sanctioned_amount: 6925599415,
    total_disbursed_amount: 6894817994,
    high_cost_anomalies: 1119,
    high_duplicate_pairs: 2559,
    high_fund_anomalies: 1,
    high_delays: 6714,
  },
  {
    district: 'MUMBAI SUBURBAN',
    state: 'MAHARASHTRA',
    total_works: 11500,
    total_sanctioned_amount: 6150146199,
    total_disbursed_amount: 6122811346,
    high_cost_anomalies: 993,
    high_duplicate_pairs: 2273,
    high_fund_anomalies: 1,
    high_delays: 5962,
  },
  {
    district: 'MURSHIDABAD',
    state: 'WEST BENGAL',
    total_works: 10680,
    total_sanctioned_amount: 5711614035,
    total_disbursed_amount: 5686228276,
    high_cost_anomalies: 923,
    high_duplicate_pairs: 2111,
    high_fund_anomalies: 1,
    high_delays: 5537,
  },
  {
    district: 'BENGALURU URBAN',
    state: 'KARNATAKA',
    total_works: 9710,
    total_sanctioned_amount: 5192862573,
    total_disbursed_amount: 5169782449,
    high_cost_anomalies: 839,
    high_duplicate_pairs: 1919,
    high_fund_anomalies: 0,
    high_delays: 5034,
  },
  {
    district: 'FARIDKOT',
    state: 'PUNJAB',
    total_works: 8810,
    total_sanctioned_amount: 4711546783,
    total_disbursed_amount: 4690605909,
    high_cost_anomalies: 761,
    high_duplicate_pairs: 1741,
    high_fund_anomalies: 0,
    high_delays: 4568,
  },
  {
    district: 'JAIPUR',
    state: 'RAJASTHAN',
    total_works: 8430,
    total_sanctioned_amount: 4508324561,
    total_disbursed_amount: 4488286926,
    high_cost_anomalies: 728,
    high_duplicate_pairs: 1666,
    high_fund_anomalies: 0,
    high_delays: 4371,
  },
  {
    district: 'AHMEDABAD',
    state: 'GUJARAT',
    total_works: 8020,
    total_sanctioned_amount: 4289058479,
    total_disbursed_amount: 4269995391,
    high_cost_anomalies: 693,
    high_duplicate_pairs: 1585,
    high_fund_anomalies: 0,
    high_delays: 4158,
  },
  {
    district: 'CHENNAI',
    state: 'TAMIL NADU',
    total_works: 7730,
    total_sanctioned_amount: 4133967836,
    total_disbursed_amount: 4115594061,
    high_cost_anomalies: 668,
    high_duplicate_pairs: 1528,
    high_fund_anomalies: 0,
    high_delays: 4008,
  },
  {
    district: 'HYDERABAD',
    state: 'TELANGANA',
    total_works: 7350,
    total_sanctioned_amount: 3930745614,
    total_disbursed_amount: 3913275077,
    high_cost_anomalies: 635,
    high_duplicate_pairs: 1453,
    high_fund_anomalies: 0,
    high_delays: 3811,
  },
  {
    district: 'NEW DELHI',
    state: 'DELHI',
    total_works: 7020,
    total_sanctioned_amount: 3754263158,
    total_disbursed_amount: 3737577013,
    high_cost_anomalies: 606,
    high_duplicate_pairs: 1387,
    high_fund_anomalies: 0,
    high_delays: 3640,
  },
  {
    district: 'KAMRUP METROPOLITAN',
    state: 'ASSAM',
    total_works: 6640,
    total_sanctioned_amount: 3551040936,
    total_disbursed_amount: 3535258029,
    high_cost_anomalies: 574,
    high_duplicate_pairs: 1312,
    high_fund_anomalies: 0,
    high_delays: 3443,
  },
  {
    district: 'BHOPAL',
    state: 'MADHYA PRADESH',
    total_works: 6370,
    total_sanctioned_amount: 3406646199,
    total_disbursed_amount: 3391505067,
    high_cost_anomalies: 550,
    high_duplicate_pairs: 1259,
    high_fund_anomalies: 0,
    high_delays: 3303,
  },
  {
    district: 'RAIPUR',
    state: 'CHHATTISGARH',
    total_works: 6130,
    total_sanctioned_amount: 3278295322,
    total_disbursed_amount: 3263724656,
    high_cost_anomalies: 529,
    high_duplicate_pairs: 1211,
    high_fund_anomalies: 0,
    high_delays: 3178,
  },
  {
    district: 'RANCHI',
    state: 'JHARKHAND',
    total_works: 5830,
    total_sanctioned_amount: 3117856725,
    total_disbursed_amount: 3103999143,
    high_cost_anomalies: 504,
    high_duplicate_pairs: 1152,
    high_fund_anomalies: 0,
    high_delays: 3023,
  },
  {
    district: 'BHUBANESWAR',
    state: 'ODISHA',
    total_works: 5560,
    total_sanctioned_amount: 2973461988,
    total_disbursed_amount: 2960246181,
    high_cost_anomalies: 480,
    high_duplicate_pairs: 1099,
    high_fund_anomalies: 0,
    high_delays: 2883,
  },
  {
    district: 'THIRUVANANTHAPURAM',
    state: 'KERALA',
    total_works: 5310,
    total_sanctioned_amount: 2839763158,
    total_disbursed_amount: 2827141587,
    high_cost_anomalies: 459,
    high_duplicate_pairs: 1049,
    high_fund_anomalies: 0,
    high_delays: 2753,
  },
  {
    district: 'VISAKHAPATNAM',
    state: 'ANDHRA PRADESH',
    total_works: 5080,
    total_sanctioned_amount: 2716760234,
    total_disbursed_amount: 2704685360,
    high_cost_anomalies: 439,
    high_duplicate_pairs: 1004,
    high_fund_anomalies: 0,
    high_delays: 2634,
  },
  {
    district: 'SRINAGAR',
    state: 'JAMMU AND KASHMIR',
    total_works: 4840,
    total_sanctioned_amount: 2588409357,
    total_disbursed_amount: 2576904949,
    high_cost_anomalies: 418,
    high_duplicate_pairs: 956,
    high_fund_anomalies: 0,
    high_delays: 2509,
  },
  {
    district: 'DEHRADUN',
    state: 'UTTARAKHAND',
    total_works: 4580,
    total_sanctioned_amount: 2449362573,
    total_disbursed_amount: 2438476171,
    high_cost_anomalies: 396,
    high_duplicate_pairs: 905,
    high_fund_anomalies: 0,
    high_delays: 2375,
  },
  {
    district: 'SHIMLA',
    state: 'HIMACHAL PRADESH',
    total_works: 4340,
    total_sanctioned_amount: 2321011696,
    total_disbursed_amount: 2310695760,
    high_cost_anomalies: 375,
    high_duplicate_pairs: 858,
    high_fund_anomalies: 0,
    high_delays: 2250,
  },
  {
    district: 'GURUGRAM',
    state: 'HARYANA',
    total_works: 4130,
    total_sanctioned_amount: 2208704678,
    total_disbursed_amount: 2198887901,
    high_cost_anomalies: 357,
    high_duplicate_pairs: 816,
    high_fund_anomalies: 0,
    high_delays: 2141,
  },
  {
    district: 'IMPHAL WEST',
    state: 'MANIPUR',
    total_works: 3920,
    total_sanctioned_amount: 2096397661,
    total_disbursed_amount: 2087080041,
    high_cost_anomalies: 339,
    high_duplicate_pairs: 775,
    high_fund_anomalies: 0,
    high_delays: 2032,
  },
  {
    district: 'SHILLONG',
    state: 'MEGHALAYA',
    total_works: 3690,
    total_sanctioned_amount: 1973394737,
    total_disbursed_amount: 1964623814,
    high_cost_anomalies: 319,
    high_duplicate_pairs: 729,
    high_fund_anomalies: 0,
    high_delays: 1913,
  },
  {
    district: 'AGARTALA',
    state: 'TRIPURA',
    total_works: 3480,
    total_sanctioned_amount: 1861087719,
    total_disbursed_amount: 1852815955,
    high_cost_anomalies: 301,
    high_duplicate_pairs: 688,
    high_fund_anomalies: 0,
    high_delays: 1804,
  },
  {
    district: 'AIZAWL',
    state: 'MIZORAM',
    total_works: 3270,
    total_sanctioned_amount: 1748780702,
    total_disbursed_amount: 1741008096,
    high_cost_anomalies: 282,
    high_duplicate_pairs: 646,
    high_fund_anomalies: 0,
    high_delays: 1695,
  },
  {
    district: 'KOHIMA',
    state: 'NAGALAND',
    total_works: 3050,
    total_sanctioned_amount: 1631125731,
    total_disbursed_amount: 1623876053,
    high_cost_anomalies: 263,
    high_duplicate_pairs: 603,
    high_fund_anomalies: 0,
    high_delays: 1581,
  },
  {
    district: 'GANGTOK',
    state: 'SIKKIM',
    total_works: 2850,
    total_sanctioned_amount: 1524166667,
    total_disbursed_amount: 1517392377,
    high_cost_anomalies: 246,
    high_duplicate_pairs: 563,
    high_fund_anomalies: 0,
    high_delays: 1478,
  },
  {
    district: 'PANAJI',
    state: 'GOA',
    total_works: 2640,
    total_sanctioned_amount: 1411859649,
    total_disbursed_amount: 1405584518,
    high_cost_anomalies: 228,
    high_duplicate_pairs: 522,
    high_fund_anomalies: 0,
    high_delays: 1369,
  },
  {
    district: 'ITANAGAR',
    state: 'ARUNACHAL PRADESH',
    total_works: 2420,
    total_sanctioned_amount: 1294204678,
    total_disbursed_amount: 1288452474,
    high_cost_anomalies: 209,
    high_duplicate_pairs: 478,
    high_fund_anomalies: 0,
    high_delays: 1255,
  },
];
